### ISSUE TITLE
EnergyConfig

### ISSUE THREAD

**Issue by satinebm** [TrimVa/T-InfoDIN#1]
Bonjour,
Après branchement et configuration du module T-InfoDIn, vérification que le compteur est bien en mode Historique, aucune information n'est remonté, tout est à 0.
Je tente de voir si le module est bien en mode historique avec la commande EnergyConfig (Consoles - EnergyConfig) - aucun retour
Je mets à jour le firmware en version Tasmota 12.3.1 puis je reteste.
Hélas toujours aucune info de remonté et rien avec la commande EnergyConfig

Retour consoles
```
19:22:50.311 MQT: Connecté
19:22:50.316 MQT: tele/tasmota_2A0AA9/LWT = Online (persistant)
19:22:50.318 MQT: cmnd/tasmota_2A0AA9/POWER = 
19:22:51.458 MQT: stat/tasmota_2A0AA9/STATUS = {"Status":{"Module":0,"DeviceName":"Tasmota","FriendlyName":["Tasmota"],"Topic":"tasmota_2A0AA9","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
19:22:52.159 MQT: stat/tasmota_2A0AA9/STATUS1 = {"StatusPRM":{"Baudrate":9600,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"https://github.com/TrimVa/T-InfoDIN/blob/main/Firmware/Tinfo_Tasmota_D1-Mini_12.3.1_FR.bin.gz","RestartReason":"Software/System restart","Uptime":"0T00:27:21","StartupUTC":"2023-02-15T17:55:31","Sleep":50,"CfgHolder":4617,"BootCount":11,"BCResetTime":"2023-01-29T12:23:20","SaveCount":25,"SaveAddress":"3FB000"}}
19:22:52.207 MQT: stat/tasmota_2A0AA9/STATUS2 = {"StatusFWR":{"Version":"12.3.1(TasmoCompiler-esp82664M)","BuildDateTime":"2023-02-10T20:24:46","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"456/699"}}
19:22:52.258 MQT: stat/tasmota_2A0AA9/STATUS11 = {"StatusSTS":{"Time":"2023-02-15T19:22:52","Uptime":"0T00:27:21","UptimeSec":1641,"Heap":13,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":3,"Wifi":{"AP":1,"SSId":"Freebox-66AB5D","BSSId":"70:FC:8F:B6:DD:38","Channel":11,"Mode":"11n","RSSI":22,"Signal":-89,"LinkCount":1,"Downtime":"0T00:00:13"}}}
19:22:52.310 MQT: stat/tasmota_2A0AA9/STATUS10 = {"StatusSNS":{"Time":"2023-02-15T19:22:52","ENERGY":{"TotalStartTime":"2023-01-29T12:23:20","Total":0.000,"Yesterday":0.000,"Today":0.000,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
19:24:01.278 CMD: EnergyConfig
```

**Comment by TrimVa** [comment]
Bonjour,
D'après la ligne ""Baudrate":9600" dans la console il semblerai que le module soit configurer pour le mode standard de la TIC, pour le mode historique il devrait être en 1200, je vous laisse regarder dans la documentation Tasmota pour passer d'un mode à l'autre, pour la commande energyconfig effectivement cela ne remonte plus les informations du mode actuelle, j'ai eu plusieurs retours à ce sujet, je suspecte un bug côté Tasmota, je vous conseille l'excellent forum ch2i tenue par Charle Hallard à l'origine du projet Teleinfo (et accessoirement le dev de la librairie Teleinfo inclut dans Tasmota)
Cordialement
PS: quel modèle de hardware utiliser vous ?
--
Envoyé depuis l'application myMail pour Android mercredi, 15 février 2023, 07:25PM +01:00 de satinebm  ***@***.*** :
